# Generated by Django 2.0 on 2018-01-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('sett', models.FloatField()),
                ('sett_unit', models.CharField(choices=[('IN', 'yarns/inch'), ('CM', 'yarns/cm')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='YarnManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YarnNumberingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('help', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='yarn',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.YarnManufacturer'),
        ),
        migrations.AddField(
            model_name='yarn',
            name='numbering_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.YarnNumberingSystem'),
        ),
    ]
