# Generated by Django 2.0 on 2018-01-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarnnumberingsystem',
            name='code',
        ),
        migrations.AlterField(
            model_name='yarnnumberingsystem',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
