# Generated by Django 2.0 on 2018-01-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('name_text', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('thickness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YarnManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='yarn',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.YarnManufacturer'),
        ),
    ]
