# Generated by Django 2.0 on 2018-01-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180101_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='create_date',
        ),
    ]
