# Generated by Django 2.0 on 2018-01-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180106_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='sett',
            field=models.IntegerField(),
        ),
    ]
