# Generated by Django 2.0 on 2018-01-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_yarn_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='create_date',
        ),
    ]
