# Generated by Django 2.0 on 2018-01-09 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20180106_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='finished_lenght',
            field=models.FloatField(help_text='Finished lenght of the weave in m'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(error_messages={'required': 'We really need you to fill in the name. Sory for bothering you'}, max_length=200),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(\\d+([,.]?\\d*)?){1}[ ]*([xX*/]{1}[ ]*\\d*)?', message='Examples: "1.2" "5.3x2" "4,6/2"')]),
        ),
    ]
