# Generated by Django 2.0 on 2018-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20180120_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='finished_lenght',
            new_name='finished_lenght_m',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='finished_width',
            new_name='finished_width_cm',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='fringe_lenght',
            new_name='fringe_lenght_m',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='warp_shrinkage',
            new_name='lenght_shrinkage_p',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='warp_take_up',
            new_name='lenght_take_up_p',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='loom_waste_lenght',
            new_name='loom_waste_lenght_m',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='test_lenght',
            new_name='test_piece_lenght_m',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='warp_lenght',
            new_name='warp_lenght_m',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='weft_draw_in',
            new_name='width_draw_in_p',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='weft_shrinkage',
            new_name='width_shrinkage_p',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='selvedge_width',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tying_lenght',
        ),
        migrations.AddField(
            model_name='plan',
            name='cutting_margin_m',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='plan',
            name='headings_hems_lenght_m',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_desigs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_ends',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_pics',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='number_of_test_pieces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='selvedge_warps',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='warp_demand_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='warp_width_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='weft_demand_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
