# Generated by Django 2.0 on 2018-01-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20180121_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cutting_margin_m',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ends_per_cm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='finished_lenght_m',
            field=models.DecimalField(decimal_places=2, help_text='Finished lenght of the weave in m', max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='finished_width_cm',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='fringe_lenght_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='headings_hems_lenght_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='some help text', max_digits=4, verbose_name='some label'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='loom_waste_lenght_m',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='picks_per_cm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='test_piece_lenght_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='plan',
            name='warp_demand_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='warp_lenght_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='warp_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weft_demand_g',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
