# Generated by Django 2.0 on 2018-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20180122_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='finished_width_cm',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='warp_lenght_m',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='warp_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
