# Generated by Django 2.0 on 2018-01-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20180122_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='warp_lenght_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
