# Generated by Django 2.0 on 2018-01-25 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20180123_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='headings_hems_lenght_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='some help text', max_digits=4, verbose_name='Heading and hems'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(\\d+[,.]?\\d*){1}[ ]*(?:([xX*/]{1})[ ]*(\\d+))?', message='Examples: "1.2" "5.3x2" "4,6/2"')]),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='numbering_system',
            field=models.CharField(choices=[('TEX', 'TEX'), ('NEP', 'NEP'), ('NE', 'NE'), ('NM', 'NM'), ('DEN', 'DEN')], max_length=3),
        ),
    ]
