# Generated by Django 2.0 on 2018-01-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20180125_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YarnNumberingSystem',
        ),
    ]
