# Generated by Django 2.0 on 2018-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_delete_yarnnumberingsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='numbering_system',
            field=models.CharField(choices=[('TEX', 'tex (g/1.000m)'), ('DTEX', 'dtex (g/10.000m)'), ('DEN', 'den (Denier, g/9.000m)'), ('NM', 'Nm (Metric yarn number, m/g)'), ('NE', 'Ne (English cotton yarn number) aka ECC'), ('NEL', 'NeL (English linen yarn number)'), ('NEK', 'NeK (English wool yarn number, worsted)')], max_length=4),
        ),
    ]
