# Generated by Django 2.0 on 2018-02-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20180130_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
